version: '3.9'

services:
  docker_base:
    build:
      context: services/docker_base
    image: docker_base
    volumes:
      - ./common:/app/common
      - ./lib:/app/lib
      - ./data:/data
    environment:
      - PYTHONPATH=/app:$PYTHONPATH

  jupyter:
    build:
      context: services/jupyter
      args:
        base_image: docker_base
    ports:
      - 1234:1234
    volumes:
      - ./common:/app/common
      - ./lib:/app/lib
      - ./data:/data
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
